services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "33065:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      exercise_networki:
        ipv4_address: 11.168.100.100 
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./pijaossalud:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      exercise_networki:
        ipv4_address: 11.168.100.101  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./pijaossalud:/var/www/html
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database" 
    ports:
      - "9000:80"
    networks:
      exercise_networki:
        ipv4_address: 11.168.100.102

networks:
  exercise_networki:
    ipam:
      driver: default
      config:
        - subnet: "11.168.100.0/24"
volumes:
  db_data: